### ISSUE TITLE
Birthdays not shown on startup

### ISSUE THREAD

**Issue by ascherer** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#1] opened 2020-11-01 13:06 UTC
* Kubuntu 20.04.1 LTS
* Thunderbird 78.4.0 (64 bit)
* Geburtstagskalender 1.0

After adding “Geburtstagskalender” add-on in TB, birthdays are correctly shown in the “Neue Termine“ sidebar and in the “Kalender” tab.

However, when I shut down TB and restart it, the birthdays are _not_ displayed. I have to (?) open the “Kalender“ tab and click on the “eye” next to the “Geburtstage in Persönliches Adressbuch” twice to bring them back.

**Comment by ascherer** [comment] 2020-11-01 13:17
Could be a faulty xpi on Mozilla extensions. After replacing “geburtstagskalender-1.0-tb.xpi” with “birthdaycalendar.xpi” from the “releases assets” here on Github, the effect of missing birthdays in the sidebar and the calendar tab is no longer present.

**Comment by rsjtdrjgfuzkfg** [comment] 2020-11-01 15:26
I this is likely a caching issue, but do not yet understand where it could come from. Re-installing the very same XPI fixes or clearing the cache fixes the issue immediately, and it does not reappear on updates.

So I do not think the XPI served by ATN is faulty; this is probably caused by something within Thunderbird. I'm unsure if further workarounds for caching issues would be reasonable, though, given that they would likely reduce everyday performance.

Let's leave this open for now.

**Comment by ascherer** [comment] 2020-11-04 08:44
Update: I still have no idea, why the _first_ installation of `geburtstagskalender-1.0-tb.xpi` (downloaded from within TB from the Mozilla site) failed (repeatedly) to show the birthday entries after a restart. After `birthdaycalendar.xpi` (downloaded from GH) succeded, also `geburtstagskalender-1.0-tb.xpi` works fine (and obviously, both files are identical).

**Comment by ascherer** [comment] 2020-11-22 10:33
Update: Just today the birthdays are invisible, when I (re)start ThunderBird (78.5.0). Clicking the “eye” twice brings them back.

**Comment by rsjtdrjgfuzkfg** [comment] 2020-11-22 17:44
@ascherer to make sure this is still the same issue: does clearing caches fix the problem?

**Comment by ascherer** [comment] 2020-11-22 18:57
Negative. After clearing the cache (46 MB) and restarting TB, the birthdays are _not_ displayed.

For the time being, I'll try to train myself to _minimize_ TB for system stand-by, instead of closing the program.

**Comment by rsjtdrjgfuzkfg** [comment] 2020-11-23 05:18
Did you clear the startup cache with the following command through the error console?
`Services.obs.notifyObservers(null, "startupcache-invalidate", null);`
If not, does that help?

I think I have a STR for an issue that can get resolved with this cache invalidation, so I'm trying to understand if you have the same issue or if there are multiple (potentially related) bugs. In 78.5.0, bluntly deleting all cache folders fixes my issue only for a single restart, but _causes_ it to appear on subsequent restarts.

**Comment by ascherer** [comment] 2020-11-23 15:39
Indeed, it helps. Even on multiple restarts the birthdays show up as expected.

**Comment by ascherer** [comment] 2020-12-02 10:01
After today's update to TB 78.5.1, I had to clear the cache(s) to bring up the birthday calendar again.

**Comment by rsjtdrjgfuzkfg** [comment] 2020-12-15 22:05
This is [Thunderbird bug 1679723](https://bugzilla.mozilla.org/show_bug.cgi?id=1679723).

**Comment by rsjtdrjgfuzkfg** [comment] 2021-03-04 22:22
Patch landed; should be fixed in Thunderbird the upcoming Thunderbird 78.9.

**Closed by rsjtdrjgfuzkfg** 2021-03-04 22:22 UTC
Labels: bug, upstream
