### ISSUE TITLE
Thunderbird 125

### ISSUE THREAD

**Issue by MattGapp** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#32] opened 2024-04-27 05:48 UTC
The birthday calendar is only working in Thunderbird 115.10.1 .
Will there be an update for Thunderbird 125.0 ? The addon is deactivated and cannot be activated.

**Comment by rsjtdrjgfuzkfg** [comment] 2024-04-27 12:34
Duplicate of #31; I only support official release versions of Thunderbird.

**Closed by rsjtdrjgfuzkfg** 2024-04-27 12:34 UTC
